# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='delta',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='get_data.Device'),
            preserve_default=False,
        ),
    ]
